### ISSUE TITLE
Farbe der Legende

### ISSUE THREAD

**Issue by TomTomRixRix** [drogenfrosch2/profbremse#10]
Es wäre super, wenn die Farbe der Legende sich anpassen würde, sodass sie die Farbe des Balkens annimmt, für den man gestimmt hat. Alternativ sollte keine Farbe angezeigt werden, da es so momentan verwirrend ist.

<img width="530" alt="Bildschirmfoto 2020-05-11 um 23 28 15" src="https://user-images.githubusercontent.com/13121269/81618501-633aa800-93df-11ea-9d3f-3814687ff4d4.png">

**Comment by timo-braungardt** [comment]
quickfix, label ist jetzt weg, weil es schwerer wäre, die farbe zu ändern.
